Provide mechanism for skipping retries w/o acknowledging job
taylorchu/work pull request #31
Opened 2020-10-08 19:06 UTC by nyergler

Prior to this commit a job could fail in one of two ways: it could
fail with an Unrecoverable error, in which case it'd be ack'd and
removed from the queue; or it could fail with another error and be
retried with exponential backoff.

There are some situations where neither is desirable; for example, you
might want to delay processing a job by manually re-Enqueuing it
without exponential backoff.

This commit introduces a new error, ErrDoNotRetry, and makes
ErrUnrecoverable wrap it. Rather than testing for equality to
ErrUnrecoverable when determining if we should retry, we check if the
error Is (or wraps) ErrDoNotRetry.

This allows the handler (or more likely handler middleware) to more
precisely control the processing of a job.

2020-10-13 08:48 UTC, taylorchu commented
I am going to add a backoff function options, which can cover constant backoff.
But you can also add your handler middleware to enqueue, and simply return nil.

2020-10-21 19:49 UTC, nyergler commented
That was what I tried first, @taylorchu; however, I found that unless I completely re-enqueued (with a new job ID, etc) that returning `nil` caused the job the be `ack`'d, which I wanted to avoid.

Do you suggest assigning new job IDs when re-enqueuing?

2020-10-21 22:27 UTC, taylorchu requested changes
lgtm, added some suggestions.

2020-10-21 22:27 UTC, taylorchu commented on worker.go
> +	ErrDoNotRetry = errors.New("do not retry")
need to add a prefix "work: " to be clear for package user that it is from this package

2020-10-21 22:27 UTC, taylorchu commented on worker.go
> +	ErrUnrecoverable = fmt.Errorf("work: permanent error%w", ErrDoNotRetry)
need to be `: %w`. this printf pattern seems wrong.

2020-10-21 22:27 UTC, taylorchu commented on worker.go
> +			if err != ErrUnrecoverable {
need to move this to be clearer
in err != nil block,
```
if err == ErrUnrecoverable {
  return nil // ack
}
if errors.Is(err, ErrDoNotRetry) {
   // don't ack and don't reenqueue
   return err
}
// ... reenqueue logic
return err
```

2020-10-21 22:27 UTC, taylorchu commented on worker_test.go
> +		return fmt.Errorf("recoverable, but not retried%w", ErrDoNotRetry)
need to fix printf format

2021-01-06 19:59 UTC, nyergler commented
@taylorchu Apologies for dropping the ball on this, and thank you for shepherding it across the line. Much appreciated. 🙇‍♂️

2021-01-06 19:59 UTC, closed without merging